#VERSION 0.0.1
#FROM jamesanglin/numpy-scipy:latest
FROM deeplearning:latest
#RUN apk add gcc
#RUN apk add python-numpy
COPY . /app
WORKDIR /app

#RUN pip install -r requirements.txt
#RUN pip install matplotlib
#启动指令
CMD [ "python", "./MyMachineLearning/network/main.py" ]
